import { AppSidebar } from '@/components/app-sidebar';
import Header from '@/components/main/Header';
import { SidebarProvider } from '@/components/ui/sidebar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className='w-full'>
        <Header />
        {children}
      </main>
    </SidebarProvider>
  );
}
